version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                docker info
                if [[ -e ~/docker/godot_android_template_builder.docker.bin ]]; then docker load --input ~/docker/godot_android_template_builder.docker.bin; fi
                docker build --rm=false -t jonathanschmalhofer/godot-android-template-builder:latest .
                mkdir -p ~/docker; docker save jonathanschmalhofer/godot-android-template-builder:latest > ~/docker/godot_android_template_builder.docker.bin
            - run: |
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                docker push jonathanschmalhofer/godot-android-template-builder:latest
            - store_artifacts:
                path: ~/docker
    create_template:
        docker:
            - image: jonathanschmalhofer/godot-android-template-builder:latest
        steps:
            - setup_remote_docker
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p ~/my_project && \
                    cd ~/my_project
            - run:
                name: Checkout Godot
                command: |
                    cd ~/my_project && \
                    git clone https://github.com/godotengine/godot.git
            - run:
                name: Build Android Template using Scons and Cradle
                command: |
                    scons platform=android target=release android_arch=armv7 && \
                    scons platform=android target=release android_arch=arm64v8 && \
                    scons platform=android target=release android_arch=x86 && \
                    cd platform/android/java && \
                    ./gradlew build